# Generated by Django 4.2.7 on 2023-11-03 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='note',
            name='is_competed',
        ),
    ]
